# Generated by Django 4.2.30 on 2026-05-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
    ]
